[package]
name = "wasi-net-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"

[target.wasm32-wasi.dependencies]
wasi = "0.11.0+wasi-snapshot-preview1"